### ISSUE TITLE
生产issue提交自动化 for ￥200 [张150 童50]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/manufacture#1087]
1. 利用github action 发布生产issue
2. 数据来源 offersku.json
3.  创建issue 方法参照（仅仅为了参照 gh命令也可以）
```
name: build
on:
  push:
    branches: [ main ]
    paths: 
      - 'list/lists'
jobs:
  getlist:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.set-list.outputs.list }}
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - id: set-list
      run: |
        cd list
        echo "::set-output name=list::{\"include\":$(jq -R -n -c '[inputs|split("\r")|{"title":.[0]}] ' lists)}" 
        
  create-issue:
    needs: getlist
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.getlist.outputs.list)}}
      
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        
      - name: Creating vendor archive
        run: |
          pip install Jinja2 jinja2-cli
          cd list && jinja2 issue.jinja2 -D name=${{ matrix.title }} > ${{ matrix.title }}_issue.md
          
      - name: Create new issues
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: 开源软件知识产权-${{ matrix.title }}
          content-filepath: ./list/${{ matrix.title }}_issue.md
          token: ${{secrets.GITHUB_TOKEN}}
      
  clear-file:
    needs: create-issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        
      - name: Creating vendor archive
        run: |
          pip install Jinja2 jinja2-cli
          cd list && python3 create.py
      
      - name: Clear file
        run: |
          cd list && echo "" > lists
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: new vendor
```
